# version: '20.10'

# services: 
#   mysqldb:
#     image: mysql
#     restart: always
#     env_file: ./.env
#     environment:
#       MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
#       MYSQL_DATABASE: $MYSQL_DATABASE
#     ports:
#       - $MYSQL_LOCAL_PORT:$MYSQL_DOCKER_PORT
#     volumes: 
#       - db-config:/etc/mysql
#       - db-data:/var/lib/mysql
#       - ./db/backup/files/:/data_backup/data
#   app:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     # command: bash -c 'while !</dev/tcp/db/3306; do sleep 1; done; npm start'
#     image: mha-app
#     restart: always
#     env_file: ./.env
#     ports:
#       - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
#     depends_on:
#       - mysqldb 
#     stdin_open: true
#     tty: true

# volumes: 
#   db-config:
#   db-data:

# # version: "20.10"

# # networks:
# #   app-tier:
# #     driver: bridge

# # services:
# #   db:
# #     image: mysql
# #     command: --default-authentication-plugin=mysql_native_password
# #     restart: always
# #     env_file: ./.env
# #     expose:
# #       - "3306"
# #     ports:
# #       - $MYSQL_LOCAL_PORT:$MYSQL_DOCKER_PORT    
# #     networks:
# #       - app-tier      
# #     environment:
# #       MYSQL_DATABASE: $MYSQL_DATABASE
# #       MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
# #   backend:
# #     depends_on:
# #       - db
# #     build: .
# #     env_file: ./.env
# #     command: bash -c 'while !</dev/tcp/db/3306; do sleep 1; done; npm start'
# #     ports:
# #       - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
# #     networks:
# #       - app-tier

version: "20.10"

services: 
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports: 
      - 5500:5500
    volumes: 
      - .:/app
      - '/app/node_modules'
    depends_on: 
      - mysql_server
  
  mysql_server:
    image: mysql:8.0
    environment: 
      - MYSQL_DATABASE=mental_health
      - MYSQL_USER=root
      - MYSQL_PASSWORD=Sahana12*
      - MYSQL_ROOT_PASSWORD=Sahana12*